title: gdev
email: gustavdlima@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  @gstvmrtns
show_downloads:true
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
